{% set name = "asdf-standard" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asdf_standard-{{ version }}.tar.gz
  sha256: 01535bc2b15bfc09ec8a62d4999f9cf32dc49dc71660c8425640228fd8776102

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
    - setuptools-scm
  run:
    - python >=3.9

test:
  imports:
    - asdf_standard
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asdf-format/asdf-standard
  summary: The ASDF Standard schemas
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jhunkeler
    - WilliamJamieson
    - braingram
