{% set name = "asdf-standard" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/asdf_standard-{{ version }}.tar.gz
  sha256: 5942caf7d143f39f72f634484373c7f40ce48571d1db3c271e13858e33fe5966

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
  run:
    - python >={{ python_min }}

test:
  imports:
    - asdf_standard
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/asdf-format/asdf-standard
  summary: The ASDF Standard schemas
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eslavich
    - jhunkeler
    - braingram
    - nden
